created_at: '2026-01-09'
description: 明和ライブスの在庫物件（45件）を、RAM管理を行わない他社管理物件として販売するプロジェクト
phases:
  1_initiating:
    description: 立ち上げフェーズ - プロジェクト憲章、ステークホルダー分析
    name: 1_initiating
    status: completed
  2_planning:
    description: 計画フェーズ - リサーチ、発見、WBS、リスク計画、スコープ定義、PRD
    name: 2_planning
    status: in_progress
  3_executing:
    description: 実行フェーズ - スプリントゴール、会議議事録、開発実装
    name: 3_executing
    status: not_started
  4_monitoring:
    description: 監視・コントロールフェーズ - ステータスレポート、変更要求、リスク更新
    name: 4_monitoring
    status: not_started
  5_closing:
    description: 終結フェーズ - Lessons Learned、移管ドキュメント、完了報告
    name: 5_closing
    status: not_started
program_name: default
project_name: MEIWA_LIVES_2026_他社管理物件販売
status: planning
