created_at: '2025-10-16'
description: 500名規模の法務研修を3グループで並行運営する自動化LMSシステム
phases:
  1_initiating:
    description: 立ち上げフェーズ - プロジェクト憲章、ステークホルダー分析
    name: 1_initiating
    status: not_started
  2_discovery:
    description: 発見フェーズ - 仮説マップ、ペルソナ、課題定義、ユーザージャーニー
    name: 2_discovery
    status: not_started
  2_research:
    description: リサーチフェーズ - 顧客調査、競合調査、市場分析
    name: 2_research
    status: not_started
  3_planning:
    description: 計画フェーズ - WBS、リスク計画、スコープ定義、PRD
    name: 3_planning
    status: not_started
  4_executing:
    description: 実行フェーズ - スプリントゴール、会議議事録、開発実装
    name: 4_executing
    status: not_started
  5_monitoring:
    description: 監視・コントロールフェーズ - ステータスレポート、変更要求、リスク更新
    name: 5_monitoring
    status: not_started
  6_closing:
    description: 終結フェーズ - Lessons Learned、移管ドキュメント、完了報告
    name: 6_closing
    status: not_started
program_name: legal_department
project_name: legal_training_lms
status: planning
